# This workflow will build a Java project with Maven
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-maven

name: Java CI with Maven

on:
  workflow_dispatch:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    name: build
    runs-on: ubuntu-latest

    steps: 
    - uses: actions/checkout@v2
    - name: Set up JDK 11
      uses: actions/setup-java@v2
      with:
        java-version: '11'
        distribution: 'adopt'
    - name: Build with Maven
      run:  mvn -B package --file pom.xml
      
  notification:
    needs: build
    runs-on: ubuntu-latest
    steps:
    - name: Send a message to Microsoft Teams
      uses: aliencube/microsoft-teams-actions@v0.8.0
      if: always()
      with:
        webhook_uri: ${{ secrets.MS_TEAMS_WEBHOOK_URI }}
        title: CI pipeline
        text: Build is successfull waiting for the approval to run test
        theme_color: 28a745
  QA:
    name: test
    needs: build
    runs-on: ubuntu-latest
    environment:
      name: QA
    steps: 
    - uses: actions/checkout@v2
    - name: Set up JDK 11
      uses: actions/setup-java@v2
      with:
        java-version: '11'
        distribution: 'adopt'
    - name: Test with Maven
      run: mvn -B test --file pom.xml
  notify:
    needs: QA
    runs-on: ubuntu-latest
    steps:
    - name: Send a message to Microsoft Teams
      uses: aliencube/microsoft-teams-actions@v0.8.0
      if: always()
      with:
        webhook_uri: ${{ secrets.MS_TEAMS_WEBHOOK_URI }}
        title: CI pipeline
        text: Test is successful waiting for the approval to deploy
        theme_color: 28a745
        #sections: '[{ "activityImage": "https://github.githubassets.com/images/modules/logos_page/GitHub-Mark.png", "activityTitle": "GitHub Action invoked",  "activitySubtitle": "Event triggered by ${{ github.event.head_commit.author.name }}", "activityText": "Commit message: [${{ github.event.head_commit.message}}](${{ github.event.head_commit.url }})" }]'
        #sections: '[{"activityImage": "https://github.githubassets.com/images/modules/logos_page/GitHub-Mark.png", "activityTitle": "Approve or Decline the workflow", "activitySubtitle": "Event triggered by ${{ github.event.head_commit.author.name }}"}]'
        #actions: '[{ "@type": "OpenUri", "name": "View Status", "targets": [{ "os": "default", "uri": "${{ github.event.head_commit.url }}" }] }]'
        #actions: '[{ "@type": "OpenUri", "name": "Approve", "name": "Decline" "targets": [{ "os": "default", , "uri": "${{ github.event.approve_button.url }}" }] }]'
  DeployStaging:
    name: Deploy to Staging
    needs: QA
    runs-on: ubuntu-latest
    environment:
      name: staging
    steps:
      - uses: actions/checkout@v2
      - name: Login to Docker Hub
        run: docker login docker.io --username "${{ secrets.Docker_Username }}" --password "${{ secrets.Docker_Password }}"
      - name: Build the Docker Image 
        run: docker build . --file Dockerfile --tag  hasinireddy24/samplenodejs
      - name: Push the Docker Image 
        run: docker push hasinireddy24/samplenodejs:latest
    
  
    
